# Base configuration
baseURL = "/"
languageCode = "en-US"
title = "Graham Plata"
theme = "etch"
googleAnalytics = "UA-11254643-2"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Graham Plata's Digital Sandbox"
  copyright = "Copyright © 2022 Graham Plata"
  dark = "auto"
  highlight = true
  # Set to true to display page title in table of contents in blog posts.
  showPageTitleInTOC = false

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true

# Controls the navigation
[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    title = "about"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "posts"
    title = "posts"
    url = "/posts/"
    weight = 20


[permalinks]
  posts = "/posts/:title/"
