name = "nyx"
license = "MIT"
licenselink = "https://github.com/grahamplata/nyx/blob/master/LICENSE.md"
description = "A simple theme for Hugo."
tags = ["blog", "clean", "minimal"]
features = ["blog", "syntax highlighting"]
min_version = 0.30

[author]
  name = "Graham Plata"
  homepage = "https://grahamplata.com"
  twitter = "https://twitter.com/grahamplata"

[original]
  name = ""
  homepage = ""
  repo = ""
